# Generated by Django 3.2.8 on 2021-10-07 00:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_especialidad'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensaje', models.CharField(max_length=200)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(max_length=1)),
                ('empreaReceptor', models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, related_name='receptor', to='api.empresa')),
                ('empresaEmisor', models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, related_name='emisor', to='api.empresa')),
            ],
        ),
    ]
