# Generated by Django 3.2.8 on 2021-10-07 01:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_notificacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='notificacion',
            name='estado',
            field=models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, to='api.estado'),
        ),
    ]
