# Generated by Django 3.2.8 on 2021-10-07 01:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_anuncio_postulante_requerimiento_socio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visitante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('empresa', models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, related_name='empresaVisitada', to='api.empresa')),
                ('visitante', models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, related_name='visitante', to='api.empresa')),
            ],
        ),
    ]
